name = "Jacob A. Long"
role = "PhD Candidate, Communication"
organizations = [{name = "Ohio State University", url = ""}]
avatar = ""
email = "long.1377@osu.edu"
address = {street = "154 N Oval Mall", city = "Columbus", region = "OH", postcode = "43214", country = "United States", country_code = "US"}
twitter = "jacobandrewlong"
phone = ""
office_hours = ""
telegram = ""
logo = ""

# Color theme.
#   Choose from `default`, `ocean`, `forest`, or `coffee`.
theme = "Scarlet"
# Enable users to switch between day and night mode?
day_night = true
# Font style.
#   Choose from `default`, `classic`, or `playfair`.
font = "default"
font_size = "L"

plugins_js = [
  # "load-photoswipe", "prism_r", "prism-line-numbers", "prism"
  ]

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Description for social sharing and search engines. If undefined, author role is used in place.
description = ""

# Publication types.
#   Used to categorize publications.
#   The index of the publication type in the list is used as its unique numerical identifier.
#   The numeric ID is used in a publication's frontmatter to categorize it.
#   The language can be edited below.
#   For multi-lingual sites, copy this block to each language section at the end of this file.
publication_types = [
  'Uncategorized',  # 0
  'Conference paper',  # 1
  'Journal article',  # 2
  'Manuscript',  # 3
  'Report',  # 4
  'Book',  # 5
  'Book section'  # 6
]

# Enable Keybase in Contact section by entering your keybase.io username.
keybase = ""

# Date format (refer to Go's date format: http://flippinggodateformat.com )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-us"

[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = false

# Enable native social sharing buttons?
sharing = true

highlight = false
highlight_languages = []
code_highlighting = false

# Show estimated reading time for posts?
reading_time = true

# Display comment count? Requires commenting to be enabled.
comment_count = true

privacy_pack = false

# Display next/previous section pager?
section_pager = false

# Social/Academic Networking
#
# Icon pack "fa" includes the following social network icons:
#
#   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
#   youtube, instagram, soundcloud
#
#   For email icon, use "fa" icon pack, "envelope" icon, and
#   "mailto:your@email.com" as the link.
#
#   Full list: https://fontawesome.github.io/Font-Awesome/icons/
#
# Icon pack "ai" includes the following academic network icons:
#
#   google-scholar, arxiv, orcid, researchgate, mendeley
#
#   Full list: https://jpswalsh.github.io/academicons/

contact_links = [
  # {icon = "envelope", icon_pack = "fas", link = "mailto:long.1377@osu.edu"},
  {icon = "twitter", icon_pack = "fab", link = "//twitter.com/jacobandrewlong", name = "jacobandrewlong"},
  # {icon = "google-scholar", icon_pack = "ai", link = "https://scholar.google.com/citations?hl=en&user=fi-oVkIAAAAJ"},
  # {icon = "osf", icon_pack = "ai", link = "https://osf.io/afqty/"},
  # {icon = "orcid", icon_pack = "ai", link = "https://orcid.org/0000-0002-1582-6214"},
  # {icon = "github", icon_pack = "fab", link = "//github.com/jacob-long"}
] 


# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {align = "r", show_logo = false}

# Recommend sites links ####

# [[params.links]]
#   name = "Andrew Gelman"
#   url = "//andrewgelman.com"

# [[params.links]]
#   name = "Data Colada"
#   url = "//datacolada.org/"

# [[params.links]]
#   name = "UCLA IDRE Stats Resources"
#   url = "//www.ats.ucla.edu/stat/"

# [[params.links]]
#   name = "R-Bloggers"
#   url = "//r-bloggers.com"

# [[params.links]]
#   name = "Elements of Evolutionary Anthropology (Richard McElreath)"
#   url = "http://elevanth.org/blog/"

# [[params.links]]
#   name = "Biased and Inefficient (Thomas Lumley)"
#   url = "http://notstatschat.tumblr.com"

# Link authors to their profile page? (true/false)
link_authors = false

# Configuration of talk pages.
[talks]
  # Show talk time?
  time = false

# Configuration of publication pages.
[publications]
  # Date format (refer to Go's date format: http://fuckinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006"
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # # List publications and talks related to the project?
  # list_children = true

  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  publication_view = 2

  # Post list format.
  #   0 = Simple
  #   1 = Detailed
  #   2 = Stream
  post_view = 0
  talk_view = 2

# Search.
[search]
  # Search provider:
  #   0: No search engine
  #   1: Algolia (https://www.algolia.com)
  engine = 0

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

# Comments.
[comments]
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  engine = 1

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true}

  # Configuration of Disqus.
  [comments.disqus]
    shortname = "jacob-long"  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)

[marketing]
  google_analytics = "UA-85962705-1"
  google_tag_manager = ""

############################
## Maps
############################
[map]
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  engine = 0
  api_key = ""
  zoom = 15

