baseurl = "https://www.jacob-long.com/"
title = "Jacob Long"
copyright = "&copy; 2018 Jacob Long"
languageCode = "en-us"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enable comments by entering your Disqus shortname
disqusShortname = "jacob-long"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-85962705-1"

# Jacob add
pygmentscodefences = false
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
pygmentsUseClasses = false

preserveTaxonomyNames = true
paginate = 10

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = [ "HTML", "CSS" ]

[params]
  name = "Jacob A. Long"
  role = "PhD Student, Communication"
  organization = "Ohio State University"
#  avatar = "portrait.jpg"
  email = "long.1377@osu.edu"
  address = "154 N Oval Mall, Columbus, OH, 43210"
  twitter = "jacobandrewlong"
  phone = ""

  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, or `coffee`.
  color_theme = "default"

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "classic"
  # My CSS customizations
  custom_css = ["prismjs.css",
  "prism.tomorrownight80s.css",
  "prism_line_nos.css",
  "custombrief.css"]

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  highlight = false
  
  # Show estimated reading time for posts?
  reading_time = true

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:long.1377@osu.edu"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/jacobandrewlong"

#  [[params.social]]
#   icon = "google-scholar"
#   icon_pack = "ai"
#    link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/jacob-long"

# Recommend sites links ####

  [[params.links]]
    name = "Andrew Gelman"
    url = "//andrewgelman.com"

  [[params.links]]
    name = "Data Colada"
    url = "//datacolada.org/"

  [[params.links]]
    name = "UCLA IDRE Stats Resources"
    url = "//www.ats.ucla.edu/stat/"

  [[params.links]]
    name = "R-Bloggers"
    url = "//r-bloggers.com"

  [[params.links]]
    name = "Elements of Evolutionary Anthropology (Richard McElreath)"
    url = "http://elevanth.org/blog/"

  [[params.links]]
    name = "Biased and Inefficient (Thomas Lumley)"
    url = "http://notstatschat.tumblr.com"

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

######

# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

#[[menu.main]]
#  name = "Publications"
#  url = "#publications"
#  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3
  
[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teach"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6
  
# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Configure the English version of the website.
[Languages.en]
  languageCode = "en-us"

