# baseurl = "https://www.jacob-long.com/"
baseurl = "/"
title = "Jacob Long"
copyright = "&copy; 2019 Jacob Long"
languageCode = "en-us"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enable comments by entering your Disqus shortname
disqusShortname = "jacob-long"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-85962705-1"

# Jacob add
pygmentscodefences = false
pygmentsCodeFencesGuessSyntax = false
pygmentsStyle = "monokai"
pygmentsUseClasses = true

preserveTaxonomyNames = true
paginate = 10

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.

# Get last modified date for content from Git?
enableGitInfo = false

# Date format (refer to Go's date format: http://flippinggodateformat.com )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[menu.main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
  
# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
